USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE TRANSFORMER TO ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS NETFLIX_DATA;
GRANT OPERATE ON WAREHOUSE NETFLIX_DATA TO ROLE TRANSFORMER;

-- Creating the user with the role transformer for the data warehouse, this is the account dbt will use to do transformations
CREATE USER IF NOT EXISTS dbt_user
    PASSWORD= 'password123'
    LOGIN_NAME='dbt_user'
    MUST_CHANGE_PASSWORD=FALSE
    DEFAULT_WAREHOUSE='NETFLIX_DATA'
    DEFAULT_ROLE=TRANSFORMER
    DEFAULT_NAMESPACE='RAW_MOVIE_DATA';
ALTER USER dbt_user SET TYPE = LEGACY_SERVICE;
GRANT ROLE TRANSFORMER TO USER dbt_user;

-- create a database and schema for this project
CREATE DATABASE IF NOT EXISTS NETFLIX_DATA;
CREATE SCHEMA IF NOT EXISTS NETFLIX_DATA.RAW_MOVIE_DATA;

-- grant access to all database, schemas and tables to the role transformer
GRANT ALL ON WAREHOUSE NETFLIX_DATA TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE NETFLIX_DATA TO ROLE TRANSFORMER;
GRANT ALL ON ALL SCHEMAS IN DATABASE NETFLIX_DATA TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE NETFLIX_DATA TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA NETFLIX_DATA.RAW_MOVIE_DATA TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA NETFLIX_DATA.RAW_MOVIE_DATA TO ROLE TRANSFORMER;