models:
  - name: dim_links
    description: Dimension table that contains the link to review websites for each movie record.
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique
      - name: imdb_id
        tests:
          - not_null
          - unique
      - name: tmdb_id
        tests:
          - not_null
          - unique
      
