models:
  - name: stg_movies
    description: Dimension table that contains the all the movies within the database and some metadata.
    columns:
      - name: movie_id
        tests:
          - not_null
          - unique
      - name: title
        tests:
          - not_null
      - name: genres
        tests:
          - not_null
      
